version: "3.7"
services:
  web:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
      - /var/www/anipal:/var/www/anipal
    environment:
      - NEST_SERVER_ADDR=backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  backend:
    build: nestjs
    environment:
      - NEST_SERVER_PORT=9091
    volumes:
      - ./nestjs:/src
      - /src/node_modules
    command: 
      - bash
      - -c
      - |
        npm run start:dev